
define([
    "sax/test/attribute-name.js",
    "sax/test/attribute-no-space.js",
    "sax/test/attribute-unquoted.js",
    "sax/test/bom.js",
//    "sax/test/buffer-overrun.js",
    "sax/test/case.js",
    "sax/test/cdata-chunked.js",
    "sax/test/cdata-end-split.js",
    "sax/test/cdata-fake-end.js",
    "sax/test/cdata.js",
    "sax/test/cdata-multiple.js",
    "sax/test/cyrillic.js",
    "sax/test/duplicate-attribute.js",
    "sax/test/emoji.js",
//    "sax/test/end_empty_stream.js",
    "sax/test/entities.js",
    "sax/test/entity-mega.js",
    "sax/test/entity-nan.js",
    "sax/test/flush.js",
    "sax/test/issue-23.js",
    "sax/test/issue-30.js",
    "sax/test/issue-35.js",
    "sax/test/issue-47.js",
    "sax/test/issue-49.js",
    "sax/test/issue-84.js",
    "sax/test/issue-86.js",
//    "sax/test/not-string.js",
    "sax/test/opentagstart.js",
    "sax/test/parser-position.js",
    "sax/test/script-close-better.js",
    "sax/test/script.js",
    "sax/test/self-closing-child.js",
    "sax/test/self-closing-child-strict.js",
    "sax/test/self-closing-tag.js",
    "sax/test/stand-alone-comment.js",
    "sax/test/stray-ending.js",
    "sax/test/trailing-attribute-no-value.js",
    "sax/test/trailing-non-whitespace.js",
    "sax/test/unclosed-root.js",
    "sax/test/unquoted.js",
//    "sax/test/utf8-split.js",
    "sax/test/xml_entities.js",
    "sax/test/xml-internal-entities.js",
    "sax/test/xmlns-as-tag-name.js",
    "sax/test/xmlns-issue-41.js",
    "sax/test/xmlns-rebinding.js",
    "sax/test/xmlns-strict.js",
    "sax/test/xmlns-unbound-element.js",
    "sax/test/xmlns-unbound.js",
    "sax/test/xmlns-xml-default-ns.js",
    "sax/test/xmlns-xml-default-prefix-attribute.js",
    "sax/test/xmlns-xml-default-prefix.js",
    "sax/test/xmlns-xml-default-redefine.js"
], function() {
    
    return {
        main: function() {
        }
    };
});
