
define([
  'decimaljs/test/setup',
  'decimaljs/test/modules/abs',
  'decimaljs/test/modules/acos',
  'decimaljs/test/modules/acosh',
  'decimaljs/test/modules/asin',
  'decimaljs/test/modules/asinh',
  'decimaljs/test/modules/atan',
  'decimaljs/test/modules/atan2',
  'decimaljs/test/modules/atanh',
  'decimaljs/test/modules/cbrt',
  'decimaljs/test/modules/ceil',
  'decimaljs/test/modules/clone',
  'decimaljs/test/modules/cmp',
  'decimaljs/test/modules/config',
  'decimaljs/test/modules/cos',
  'decimaljs/test/modules/cosh',
  'decimaljs/test/modules/Decimal',
  'decimaljs/test/modules/div',
  'decimaljs/test/modules/divToInt',
  'decimaljs/test/modules/dpSd',
  'decimaljs/test/modules/exp',
  'decimaljs/test/modules/floor',
  'decimaljs/test/modules/hypot',
//  'decimaljs/test/modules/immutability',
  'decimaljs/test/modules/intPow',
  'decimaljs/test/modules/isFiniteEtc',
  'decimaljs/test/modules/ln',
  'decimaljs/test/modules/log',
  'decimaljs/test/modules/log10',
  'decimaljs/test/modules/log2',
  'decimaljs/test/modules/minAndMax',
  'decimaljs/test/modules/minus',
  'decimaljs/test/modules/mod',
  'decimaljs/test/modules/neg',
  'decimaljs/test/modules/plus',
  'decimaljs/test/modules/pow',
  'decimaljs/test/modules/random',
  'decimaljs/test/modules/round',
  'decimaljs/test/modules/sign',
  'decimaljs/test/modules/sin',
  'decimaljs/test/modules/sinh',
//  'decimaljs/test/modules/sqrt',
  'decimaljs/test/modules/tan',
//  'decimaljs/test/modules/tanh',
  'decimaljs/test/modules/times',
  'decimaljs/test/modules/toBinary',
  'decimaljs/test/modules/toDP',
  'decimaljs/test/modules/toExponential',
  'decimaljs/test/modules/toFixed',
  'decimaljs/test/modules/toFraction',
  'decimaljs/test/modules/toHex',
  'decimaljs/test/modules/toNearest',
//  'decimaljs/test/modules/toNumber',
  'decimaljs/test/modules/toOctal',
  'decimaljs/test/modules/toPrecision',
  'decimaljs/test/modules/toSD',
  'decimaljs/test/modules/toString',
  'decimaljs/test/modules/trunc',
  'decimaljs/test/modules/valueOf'
], function() {
});
