define(function(localRequire, exports, module) { var requireOrig = require; require = localRequire;
var describe = require('tape-compat').describe;
var it = require('tape-compat').it;
var assert = require('assert'),
    math = require('../../../index');

describe('pickRandom', function () {
  // Note: pickRandom is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function pickRandom', function () {
    assert.equal(typeof math.pickRandom, 'function');
  })

  it('should LaTeX pickRandom', function () {
    var expression = math.parse('pickRandom([1,2,3])');
    assert.equal(expression.toTex(), '\\mathrm{pickRandom}\\left(\\begin{bmatrix}1\\\\2\\\\3\\\\\\end{bmatrix}\\right)');
  });

});

require = requireOrig;});
