define(function(localRequire, exports, module) { var requireOrig = require; require = localRequire;
var describe = require('tape-compat').describe;
var it = require('tape-compat').it;
var assert = require('assert'),
    math = require('../../../index');

describe('randomInt', function () {
  // Note: randomInt is a convenience function generated by distribution
  // it is tested in distribution.test.js

  it('should have a function randomInt', function () {
    assert.equal(typeof math.randomInt, 'function');
  })

  it('should LaTeX randomInt', function () {
    var expression = math.parse('randomInt(0,100)');
    assert.equal(expression.toTex(), '\\mathrm{randomInt}\\left(0,100\\right)');
  });
});

require = requireOrig;});
